// flow-typed signature: d6c834eb4fbcffe0008a969366d4f650
// flow-typed version: <<STUB>>/sass-autoprefixer_v^1.0.1/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'sass-autoprefixer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'sass-autoprefixer' {
  declare module.exports: any;
}
